/*
 * pwix:editor/src/common/js/constants.js
 */

TE_MODE_HIDDEN = 'TE_MODE_HIDDEN';
TE_MODE_STANDARD = 'TE_MODE_STANDARD';
TE_MODE_PREVIEW = 'TE_MODE_PREVIEW';
TE_MODE_EDITION = 'TE_MODE_EDITION';

pwiEditor.Modes = [
    TE_MODE_HIDDEN,
    TE_MODE_STANDARD,
    TE_MODE_PREVIEW,
    TE_MODE_EDITION
];

TE_VERBOSE_NONE = 0;
TE_VERBOSE_TBWMSG = 0x01 << 0;
TE_VERBOSE_TEMSG = 0x01 << 1;
TE_VERBOSE_CREDEL = 0x01 << 2;
TE_VERBOSE_UPLOAD = 0x01 << 3;
